/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CustomerController;
import javax.swing.JOptionPane;

/**
 *
 * @author Mangal Tamang
 */
public class CreditRequest extends javax.swing.JFrame {

    /**
     * Creates new form CreditRequest
     */
    public CreditRequest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        panel_customer = new javax.swing.JPanel();
        lbl_full_name = new javax.swing.JLabel();
        text_full_name = new javax.swing.JTextField();
        lbl_dob = new javax.swing.JLabel();
        text_dob = new javax.swing.JTextField();
        lbl_address = new javax.swing.JLabel();
        text_address = new javax.swing.JTextField();
        panel_property = new javax.swing.JPanel();
        lbl_valuation = new javax.swing.JLabel();
        text_valuation = new javax.swing.JTextField();
        lbl_property_type = new javax.swing.JLabel();
        text_property_type = new javax.swing.JTextField();
        lbl_valuation_date = new javax.swing.JLabel();
        text_valuation_date = new javax.swing.JTextField();
        panel_income = new javax.swing.JPanel();
        lbl_income_source = new javax.swing.JLabel();
        text_income_source = new javax.swing.JTextField();
        lbl_annual_income = new javax.swing.JLabel();
        text_annual_income = new javax.swing.JTextField();
        panel_credit = new javax.swing.JPanel();
        lbl_credit_type = new javax.swing.JLabel();
        text_credit_type = new javax.swing.JTextField();
        lbl_credit_amount = new javax.swing.JLabel();
        text_credit_amount = new javax.swing.JTextField();
        lbl_eligible = new javax.swing.JLabel();
        text_eligible = new javax.swing.JTextField();
        lbl_credit_status = new javax.swing.JLabel();
        text_credit_status = new javax.swing.JTextField();
        btn_add_request = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Add Credit Request | Credit Manager");

        panel_customer.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Details"));

        lbl_full_name.setText("Full Name:");

        lbl_dob.setText("Date of Birth");

        lbl_address.setText("Permanent Address:");

        javax.swing.GroupLayout panel_customerLayout = new javax.swing.GroupLayout(panel_customer);
        panel_customer.setLayout(panel_customerLayout);
        panel_customerLayout.setHorizontalGroup(
            panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_customerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_customerLayout.createSequentialGroup()
                        .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_address))
                    .addGroup(panel_customerLayout.createSequentialGroup()
                        .addComponent(lbl_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_dob))
                    .addGroup(panel_customerLayout.createSequentialGroup()
                        .addComponent(lbl_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panel_customerLayout.setVerticalGroup(
            panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_customerLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panel_property.setBorder(javax.swing.BorderFactory.createTitledBorder("Property Details"));

        lbl_valuation.setText("Property Valuation:");

        lbl_property_type.setText("Property Type:");

        lbl_valuation_date.setText("Valuation Date:");

        javax.swing.GroupLayout panel_propertyLayout = new javax.swing.GroupLayout(panel_property);
        panel_property.setLayout(panel_propertyLayout);
        panel_propertyLayout.setHorizontalGroup(
            panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_propertyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_propertyLayout.createSequentialGroup()
                        .addComponent(lbl_valuation, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_valuation))
                    .addGroup(panel_propertyLayout.createSequentialGroup()
                        .addComponent(lbl_property_type, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_property_type))
                    .addGroup(panel_propertyLayout.createSequentialGroup()
                        .addComponent(lbl_valuation_date, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_valuation_date)))
                .addGap(17, 17, 17))
        );
        panel_propertyLayout.setVerticalGroup(
            panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_propertyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valuation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_valuation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_property_type, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_property_type, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valuation_date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_valuation_date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panel_income.setBorder(javax.swing.BorderFactory.createTitledBorder("Income Details"));

        lbl_income_source.setText("Income Source:");

        lbl_annual_income.setText("Annual Income:");

        javax.swing.GroupLayout panel_incomeLayout = new javax.swing.GroupLayout(panel_income);
        panel_income.setLayout(panel_incomeLayout);
        panel_incomeLayout.setHorizontalGroup(
            panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_incomeLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_incomeLayout.createSequentialGroup()
                        .addComponent(lbl_income_source, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_income_source))
                    .addGroup(panel_incomeLayout.createSequentialGroup()
                        .addComponent(lbl_annual_income, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_annual_income)))
                .addGap(19, 19, 19))
        );
        panel_incomeLayout.setVerticalGroup(
            panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_incomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_income_source, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_income_source, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_annual_income, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_annual_income, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panel_credit.setBorder(javax.swing.BorderFactory.createTitledBorder("Credit Details"));

        lbl_credit_type.setText("Credit Type:");

        lbl_credit_amount.setText("Credit Amount:");

        lbl_eligible.setText("Is Eligible");

        lbl_credit_status.setText("Credit Status:");

        javax.swing.GroupLayout panel_creditLayout = new javax.swing.GroupLayout(panel_credit);
        panel_credit.setLayout(panel_creditLayout);
        panel_creditLayout.setHorizontalGroup(
            panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_creditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_creditLayout.createSequentialGroup()
                        .addComponent(lbl_credit_type, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_credit_type))
                    .addGroup(panel_creditLayout.createSequentialGroup()
                        .addComponent(lbl_credit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_credit_amount))
                    .addGroup(panel_creditLayout.createSequentialGroup()
                        .addComponent(lbl_eligible, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_eligible))
                    .addGroup(panel_creditLayout.createSequentialGroup()
                        .addComponent(lbl_credit_status, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_credit_status)))
                .addGap(26, 26, 26))
        );
        panel_creditLayout.setVerticalGroup(
            panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_creditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_credit_type, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_credit_type, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_credit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_credit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_eligible, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_eligible, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_credit_status, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_credit_status, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_add_request.setText("Add Credit Request");
        btn_add_request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_requestActionPerformed(evt);
            }
        });

        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_property, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_income, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_credit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(btn_add_request, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_property, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_request, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_add_requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_requestActionPerformed
        // TODO add your handling code here:
        String full_name = text_full_name.getText();
        String dob = text_dob.getText();
        String address = text_address.getText();
        String property_type = text_property_type.getText();
        String valuation_date = text_valuation_date.getText();
        String income_source = text_income_source.getText();
        String credit_type = text_credit_type.getText();
        String is_eligible = text_eligible.getText();
        String credit_status = text_credit_status.getText();
        double credit_amount = 0.00;
        double property_valuation = 0.00;
        double annual_income = 0.00;
        try {
            credit_amount = Double.parseDouble(text_credit_amount.getText());
            property_valuation = Double.parseDouble(text_valuation.getText());
            annual_income = Double.parseDouble(text_annual_income.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(panel_customer, "Please enter numeric value");
        }
        // please do validation on you own
        
        CustomerController cc = new CustomerController();
        cc.full_name = full_name;
        cc.dob = dob;
        cc.address = address;
        cc.property_type = property_type;
        cc.property_valuation = property_valuation;
        cc.income_source = income_source;
        cc.valuation_date = valuation_date;
        cc.credit_type = credit_type;
        if(is_eligible.equals("Yes")){
            cc.is_eligible = 1;
        } else {
            cc.is_eligible = 0;
        }
        cc.credit_amount = credit_amount;
        cc.credit_status = credit_status;
        cc.annual_income = annual_income;
        if(cc.addCustomerCreditRequest(cc)){
            JOptionPane.showMessageDialog(panel_customer, "Credit request submitted successfully");
        } else {
            JOptionPane.showMessageDialog(panel_customer, "Something went wrong. Please try again");
        }

    }//GEN-LAST:event_btn_add_requestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_request;
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_annual_income;
    private javax.swing.JLabel lbl_credit_amount;
    private javax.swing.JLabel lbl_credit_status;
    private javax.swing.JLabel lbl_credit_type;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_eligible;
    private javax.swing.JLabel lbl_full_name;
    private javax.swing.JLabel lbl_income_source;
    private javax.swing.JLabel lbl_property_type;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_valuation;
    private javax.swing.JLabel lbl_valuation_date;
    private javax.swing.JPanel panel_credit;
    private javax.swing.JPanel panel_customer;
    private javax.swing.JPanel panel_income;
    private javax.swing.JPanel panel_property;
    private javax.swing.JTextField text_address;
    private javax.swing.JTextField text_annual_income;
    private javax.swing.JTextField text_credit_amount;
    private javax.swing.JTextField text_credit_status;
    private javax.swing.JTextField text_credit_type;
    private javax.swing.JTextField text_dob;
    private javax.swing.JTextField text_eligible;
    private javax.swing.JTextField text_full_name;
    private javax.swing.JTextField text_income_source;
    private javax.swing.JTextField text_property_type;
    private javax.swing.JTextField text_valuation;
    private javax.swing.JTextField text_valuation_date;
    // End of variables declaration//GEN-END:variables
}
