/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CustomerController;

/**
 *
 * @author Mangal Tamang
 */
public class EditCredit extends javax.swing.JFrame {
    int customer_id;
    /**
     * Creates new form EditCredit
     */
    public EditCredit() {
        initComponents();
        edit_tab_pane.add(CustomerDetail,"Customer Details", 0);
        edit_tab_pane.add(PropertyDetail,"Property Details", 1);
        edit_tab_pane.add(IncomeDetail,"Income Details", 2);
        edit_tab_pane.add(CreditDetail,"Credit Details", 3);
    }
    
    public void setCustomerCreditRequest(CustomerController cc){
        customer_id = cc.customer_id;
        text_full_name.setText(cc.full_name);
        text_dob.setText(cc.dob);
        text_address.setText(cc.address);
        text_income_source.setText(cc.income_source);
        text_annual_income.setText(cc.annual_income+ "");
        text_property_type.setText(cc.property_type);
        text_valuation.setText(cc.property_valuation + "");
        text_valuation_date.setText(cc.valuation_date);
        text_credit_amount.setText(cc.credit_amount + "");
        text_credit_status.setText(cc.credit_status);
        text_credit_type.setText(cc.credit_type);
        text_eligible.setText(cc.is_eligible + "");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerDetail = new javax.swing.JInternalFrame();
        panel_customer = new javax.swing.JPanel();
        lbl_full_name = new javax.swing.JLabel();
        text_full_name = new javax.swing.JTextField();
        lbl_dob = new javax.swing.JLabel();
        text_dob = new javax.swing.JTextField();
        lbl_address = new javax.swing.JLabel();
        text_address = new javax.swing.JTextField();
        PropertyDetail = new javax.swing.JInternalFrame();
        panel_property = new javax.swing.JPanel();
        lbl_valuation = new javax.swing.JLabel();
        text_valuation = new javax.swing.JTextField();
        lbl_property_type = new javax.swing.JLabel();
        text_property_type = new javax.swing.JTextField();
        lbl_valuation_date = new javax.swing.JLabel();
        text_valuation_date = new javax.swing.JTextField();
        IncomeDetail = new javax.swing.JInternalFrame();
        panel_income = new javax.swing.JPanel();
        lbl_income_source = new javax.swing.JLabel();
        text_income_source = new javax.swing.JTextField();
        lbl_annual_income = new javax.swing.JLabel();
        text_annual_income = new javax.swing.JTextField();
        CreditDetail = new javax.swing.JInternalFrame();
        panel_credit = new javax.swing.JPanel();
        lbl_credit_type = new javax.swing.JLabel();
        text_credit_type = new javax.swing.JTextField();
        lbl_credit_amount = new javax.swing.JLabel();
        text_credit_amount = new javax.swing.JTextField();
        lbl_eligible = new javax.swing.JLabel();
        text_eligible = new javax.swing.JTextField();
        lbl_credit_status = new javax.swing.JLabel();
        text_credit_status = new javax.swing.JTextField();
        lbl_title = new javax.swing.JLabel();
        edit_tab_pane = new javax.swing.JTabbedPane();
        btn_update = new javax.swing.JButton();

        CustomerDetail.setVisible(true);

        panel_customer.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Details"));

        lbl_full_name.setText("Full Name:");

        lbl_dob.setText("Date of Birth");

        lbl_address.setText("Permanent Address:");

        javax.swing.GroupLayout panel_customerLayout = new javax.swing.GroupLayout(panel_customer);
        panel_customer.setLayout(panel_customerLayout);
        panel_customerLayout.setHorizontalGroup(
            panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_customerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_customerLayout.createSequentialGroup()
                        .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_address))
                    .addGroup(panel_customerLayout.createSequentialGroup()
                        .addComponent(lbl_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_dob))
                    .addGroup(panel_customerLayout.createSequentialGroup()
                        .addComponent(lbl_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_customerLayout.setVerticalGroup(
            panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_customerLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CustomerDetailLayout = new javax.swing.GroupLayout(CustomerDetail.getContentPane());
        CustomerDetail.getContentPane().setLayout(CustomerDetailLayout);
        CustomerDetailLayout.setHorizontalGroup(
            CustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
            .addGroup(CustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CustomerDetailLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CustomerDetailLayout.setVerticalGroup(
            CustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
            .addGroup(CustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CustomerDetailLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        PropertyDetail.setVisible(true);

        panel_property.setBorder(javax.swing.BorderFactory.createTitledBorder("Property Details"));

        lbl_valuation.setText("Property Valuation:");

        lbl_property_type.setText("Property Type:");

        lbl_valuation_date.setText("Valuation Date:");

        javax.swing.GroupLayout panel_propertyLayout = new javax.swing.GroupLayout(panel_property);
        panel_property.setLayout(panel_propertyLayout);
        panel_propertyLayout.setHorizontalGroup(
            panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_propertyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_propertyLayout.createSequentialGroup()
                        .addComponent(lbl_valuation, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_valuation))
                    .addGroup(panel_propertyLayout.createSequentialGroup()
                        .addComponent(lbl_property_type, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_property_type))
                    .addGroup(panel_propertyLayout.createSequentialGroup()
                        .addComponent(lbl_valuation_date, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_valuation_date)))
                .addGap(17, 17, 17))
        );
        panel_propertyLayout.setVerticalGroup(
            panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_propertyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valuation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_valuation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_property_type, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_property_type, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valuation_date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_valuation_date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PropertyDetailLayout = new javax.swing.GroupLayout(PropertyDetail.getContentPane());
        PropertyDetail.getContentPane().setLayout(PropertyDetailLayout);
        PropertyDetailLayout.setHorizontalGroup(
            PropertyDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
            .addGroup(PropertyDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PropertyDetailLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_property, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PropertyDetailLayout.setVerticalGroup(
            PropertyDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
            .addGroup(PropertyDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PropertyDetailLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(panel_property, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        IncomeDetail.setVisible(true);

        panel_income.setBorder(javax.swing.BorderFactory.createTitledBorder("Income Details"));

        lbl_income_source.setText("Income Source:");

        text_income_source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_income_sourceActionPerformed(evt);
            }
        });

        lbl_annual_income.setText("Annual Income:");

        javax.swing.GroupLayout panel_incomeLayout = new javax.swing.GroupLayout(panel_income);
        panel_income.setLayout(panel_incomeLayout);
        panel_incomeLayout.setHorizontalGroup(
            panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_incomeLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_incomeLayout.createSequentialGroup()
                        .addComponent(lbl_income_source, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_income_source))
                    .addGroup(panel_incomeLayout.createSequentialGroup()
                        .addComponent(lbl_annual_income, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_annual_income)))
                .addGap(19, 19, 19))
        );
        panel_incomeLayout.setVerticalGroup(
            panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_incomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_income_source, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_income_source, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_annual_income, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_annual_income, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout IncomeDetailLayout = new javax.swing.GroupLayout(IncomeDetail.getContentPane());
        IncomeDetail.getContentPane().setLayout(IncomeDetailLayout);
        IncomeDetailLayout.setHorizontalGroup(
            IncomeDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
            .addGroup(IncomeDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(IncomeDetailLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_income, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        IncomeDetailLayout.setVerticalGroup(
            IncomeDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
            .addGroup(IncomeDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(IncomeDetailLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(panel_income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        CreditDetail.setVisible(true);

        panel_credit.setBorder(javax.swing.BorderFactory.createTitledBorder("Credit Details"));

        lbl_credit_type.setText("Credit Type:");

        lbl_credit_amount.setText("Credit Amount:");

        lbl_eligible.setText("Is Eligible");

        lbl_credit_status.setText("Credit Status:");

        javax.swing.GroupLayout panel_creditLayout = new javax.swing.GroupLayout(panel_credit);
        panel_credit.setLayout(panel_creditLayout);
        panel_creditLayout.setHorizontalGroup(
            panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_creditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_creditLayout.createSequentialGroup()
                        .addComponent(lbl_credit_type, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_credit_type))
                    .addGroup(panel_creditLayout.createSequentialGroup()
                        .addComponent(lbl_credit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_credit_amount))
                    .addGroup(panel_creditLayout.createSequentialGroup()
                        .addComponent(lbl_eligible, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_eligible))
                    .addGroup(panel_creditLayout.createSequentialGroup()
                        .addComponent(lbl_credit_status, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_credit_status)))
                .addGap(26, 26, 26))
        );
        panel_creditLayout.setVerticalGroup(
            panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_creditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_credit_type, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_credit_type, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_credit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_credit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_eligible, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_eligible, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_credit_status, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_credit_status, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CreditDetailLayout = new javax.swing.GroupLayout(CreditDetail.getContentPane());
        CreditDetail.getContentPane().setLayout(CreditDetailLayout);
        CreditDetailLayout.setHorizontalGroup(
            CreditDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
            .addGroup(CreditDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CreditDetailLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_credit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CreditDetailLayout.setVerticalGroup(
            CreditDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
            .addGroup(CreditDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CreditDetailLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Edit Credit Request | Credit Manager");

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_tab_pane)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addComponent(edit_tab_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        System.out.println(text_address.getText());
        System.out.println(text_credit_amount.getText());
        System.out.println(text_credit_status.getText());
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void text_income_sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_income_sourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_income_sourceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCredit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame CreditDetail;
    private javax.swing.JInternalFrame CustomerDetail;
    private javax.swing.JInternalFrame IncomeDetail;
    private javax.swing.JInternalFrame PropertyDetail;
    private javax.swing.JButton btn_update;
    private javax.swing.JTabbedPane edit_tab_pane;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_annual_income;
    private javax.swing.JLabel lbl_credit_amount;
    private javax.swing.JLabel lbl_credit_status;
    private javax.swing.JLabel lbl_credit_type;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_eligible;
    private javax.swing.JLabel lbl_full_name;
    private javax.swing.JLabel lbl_income_source;
    private javax.swing.JLabel lbl_property_type;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_valuation;
    private javax.swing.JLabel lbl_valuation_date;
    private javax.swing.JPanel panel_credit;
    private javax.swing.JPanel panel_customer;
    private javax.swing.JPanel panel_income;
    private javax.swing.JPanel panel_property;
    private javax.swing.JTextField text_address;
    private javax.swing.JTextField text_annual_income;
    private javax.swing.JTextField text_credit_amount;
    private javax.swing.JTextField text_credit_status;
    private javax.swing.JTextField text_credit_type;
    private javax.swing.JTextField text_dob;
    private javax.swing.JTextField text_eligible;
    private javax.swing.JTextField text_full_name;
    private javax.swing.JTextField text_income_source;
    private javax.swing.JTextField text_property_type;
    private javax.swing.JTextField text_valuation;
    private javax.swing.JTextField text_valuation_date;
    // End of variables declaration//GEN-END:variables
}
